org: iamnarcisse
app: stayr-backend-test
name: aws-lambda-starter
# component: aws-lambda

service: serverless-api

provider:
  name: aws # deploy to AWS
  stage: dev
  runtime: nodejs12.x
  versionFunctions: false # disable function versioning
  region: us-east-1 # AWS region
  apiGateway:
    shouldStartNameWithService: true
  environment:
    HASURA_ENDPOINT: https://moving-platypus-43.hasura.app/v1/graphql
    HASURA_SECRET: 6jsfuAHYuwcqKbOVPdnAp2Gxy62cLF8VXdpIcc07Bj5cYRpQY8pv2WnSucUL0ZVq
    HASURA_RELAY_ENDPOINT: https://moving-platypus-43.hasura.app/v1beta1/relay
    SENTRY_DSN: https://0ade560ebdc04f69a305240f7d05b318@o395758.ingest.sentry.io/5841524

functions:
  blog:
    handler: src/handler.server
    events:
      - http:
          path: query
          method: any
          cors: true
  pricing:
    handler: src/handler.server
    events:
      - http:
          path: price
          method: any
          cors: true
plugins:
  - serverless-offline
  - serverless-plugin-typescript
